### ISSUE TITLE
nested partials

### ISSUE THREAD

**Issue by simonmcmanus** [simonmcmanus/sizlate#21]
investigate implementing nested partials

**Comment by simonmcmanus** [comment]
v1 is coming soon which is gonna mean some changes.

All Express functionality is getting moved into its own repo:
https://github.com/simonmcmanus/sizlate-express

I've not had a chance to get it working properly yet. 

Iv'e added Array functionality to sizlate for v1. 
https://github.com/simonmcmanus/sizlate#arrays

I've also created an issue:
https://github.com/simonmcmanus/sizlate/issues/28

Once that is resolved nested selectors will have the same power as top level selectors. I think that combined with Arrays will cover most use cases.  

@richmarr - how does that sound?

**Comment by richmarr** [comment]
Makes a lot of sense to split out express.

Will check out v1 as soon as I get time :)


On Wednesday, 21 October 2015, Simon McManus <notifications@github.com>
wrote:

> v1 is coming soon which is gonna mean some changes.
>
> All Express functionality is getting moved into its own repo:
> https://github.com/simonmcmanus/sizlate-express
>
> I've not had a chance to get it working properly yet.
>
> Iv'e added Array functionality to sizlate for v1.
> https://github.com/simonmcmanus/sizlate#arrays
>
> I've also created an issue:
> #28 <https://github.com/simonmcmanus/sizlate/issues/28>
>
> Once that is resolved nested selectors will have the same power as top
> level selectors. I think that combined with Arrays will cover most use
> cases.
>
> @richmarr <https://github.com/richmarr> - how does that sound?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simonmcmanus/sizlate/issues/21#issuecomment-149994256>
> .
>


-- 
Richard Marr
